
# Executive Financial Summary Dashboard
---
## 📊 Live Interactive Report

Click below to explore the full interactive dashboard:

[🔗  View Live Report](https://app.powerbi.com/view?r=eyJrIjoiMWY3ZWQwOWYtZjA3MC00Yjk0LWJiYjktYjlkYTJiMDdmMzFhIiwidCI6IjU5MWEyZWE3LTg4MDItNGIxNS1iMDZlLTIwMGI2OTc3M2FiNiJ9)


---

<img width="800" height="450" alt="image" src="https://github.com/user-attachments/assets/6c1c56ab-4c19-4be1-87e7-9dd46687cf2c" />



A dynamic, interactive **Power BI dashboard** built to deliver high-level visibility into the company’s **financial performance**, **sales trends**, **operational costs**, and **product-level contributions**. Designed with executives and analysts in mind, this report helps monitor key business metrics and supports strategic decision-making.

## 📊 Overview

The dashboard includes slicers (filters) to dynamically explore data by:
- **Year**
- **Quarter**
- **Country**
- **Discount Rate**

It provides a consolidated view of the organisation's health through KPIs, time-based trends, and category-level insights.

---

## 🧮 Key Metrics (KPI Cards)

- **🟢 Total Sale:** `$177M`  
- **🟢 Net Sale:** `$164M`  
- **📦 Total Transactions:** `1,015`  
- **💰 Net Profit Margin:** `13%`  
- **🟥 Total COGS:** `$114M`

These figures allow quick evaluation of profitability, cost efficiency, and market performance at a glance.

---

## 📈 Visual Insights

### 1. **Sales Trend Over Time (Line Chart)**
- Sales trends across months for both 2013 and 2014.
- **Insight:** October consistently registers **peak sales** across both years.
- **Low Sales:** Seen in **August and September**.
- **Note:** This trend may indicate **seasonality**, though more historical data is needed to validate the pattern.

### 2. **Operational vs COGS Distribution (Bar Chart)**
- Compares **Operating Expenses** and **COGS** across different countries.
- **Key Finding:** COGS is **significantly higher** than operational costs in all regions.
- This signals the need to optimise supply chain or procurement strategies to improve cost efficiency.

### 3. **Segment-Level Sales Insights (Doughnut Chart)**
- Shows contribution to total sales by customer segments.
- **Top Segments:**
  - **Government**
  - **Small Business**
- These two segments contribute **~80% of total sales**, representing high-value customer groups with strategic importance.

### 4. **Product Revenue Breakdown**
- Visual comparison of revenue generated by each product.
- **Top Performer:**  
  - **Paseo** accounts for **$50M** out of **$177M** in total product revenue.
- Highlights product-level profitability and supports data-driven product lifecycle and inventory decisions.

---

## 📌 Executive Summary / Key Takeaways

- 📈 **October is the strongest sales month**, while **August–September underperform**, potentially due to seasonal demand. Additional years of data are needed for confirmation.
- 💸 **COGS dominates** total costs in every country analyzed — revealing an opportunity for efficiency improvements in sourcing and operations.
- 👥 **Government and Small Business** are the **primary revenue drivers**; strategies should focus on maintaining and growing these relationships.
- 🛒 **Product Paseo is a market leader** in revenue — consider allocating resources toward its promotion, stock availability, and complementary product bundling.

---

## 💼 Use Cases

- Boardroom presentations & monthly reviews  
- Country-level sales & cost performance tracking  
- Segment targeting and product prioritisation  
- Identifying trends and anomalies in sales behavior

---

## 🛠️ Built With

- **Power BI Desktop**
- Data model with relationships between transactions, products, customer segments, and time
- Interactive slicers and dynamic DAX measures

---

## 🏷️ Tags

`#PowerBI` `#Dashboard` `#ExecutiveSummary` `#FinancialAnalysis` `#SalesPerformance` `#COGS` `#BusinessIntelligence`  
`#SegmentAnalysis` `#ProfitabilityInsights` `#ProductAnalytics` `#DataVisualization` `#KPIs`




